name: Verify Human Identity

on:
  workflow_dispatch:
    inputs:
      agent_name:
        description: 'jiwex'
        required: true
        default: 'jiwex'
      agent_description:
        description: 'Deskripsi Agen'
        required: true
        default: 'AI Agent'

